/**
 * PROJECT REPORT BOILERPLATE — the company-level sections of Green Ecocare's real
 * Project Proposal document.
 *
 * These are the parts that are word-for-word identical across all five of the
 * client's sample PDFs regardless of technology, so they describe the COMPANY, not
 * the deal. Each is seeded into a `Company.doc*` column and edited in
 * Settings → Proposal document — exactly the `standardTermsTemplate` precedent, so
 * the office can revise its own document copy without a deploy.
 *
 * Text is the client's own, lightly cleaned for typos ("digestive" → "digestate",
 * "Hand Cloves" → "Hand Gloves") and with the per-deal specifics replaced by the
 * placeholders the renderer substitutes. Their sample's own copy-paste slips are
 * NOT reproduced — see project-report-templates.ts for that note.
 */

export const DEFAULT_DOC_INTRODUCTION = `Green Ecocare, established in 2024, has its Registered Office with Administrative and Operational Head Quarters in Coimbatore. It has its branches at Bangalore, Hyderabad, Cochin and Chennai. Green Ecocare is an environmental solutions provider that has designed, installed and commissioned over 45 environmental engineering projects, for a wide range of sizes and applications.

Green Ecocare employs fully trained technicians and engineers capable of handling design, installation, commissioning and troubleshooting service of environmental projects.

Green Ecocare is pioneering the concept of Advanced Bioengineering, to offer holistic, cost effective and eco-friendly solutions for solving the problems. This is being done in practice by adopting a combination of Biotechnology and Engineering, a concept which we call "Advanced Bioengineering", the most commonly practiced technology in advanced economies today.`;

/**
 * §5's "what this plant is" paragraph, per plant type.
 *
 * `DEFAULT_DOC_PLANT_ABOUT` is the STP text (the only one the client's samples cover)
 * and remains the Settings default. But it opens "A Sewage Treatment Plant (STP) is…",
 * so printing it verbatim under an ETP or WTP heading would state something false on a
 * customer document — the same class as the SAFF→MBBR substitution fixed in v45.
 *
 * The template therefore resolves: the company's own edited override if there is one,
 * else the entry for THIS plant type. A Project Proposal is restricted to these three
 * types (`PROJECT_REPORT_PLANT_TYPES`); anything else uses the generic layout until the
 * client supplies wording for it.
 */
export const PLANT_TYPE_ABOUT: Record<string, string> = {
  STP: `A Sewage Treatment Plant (STP) is a critical infrastructure for processing and purifying domestic and municipal wastewater. It employs a combination of physical, biological, and chemical processes to remove contaminants and pollutants, ensuring that treated water can be safely discharged into the environment or reused. STPs are essential for safeguarding public health, protecting water bodies, and promoting sustainable wastewater management practices.`,
  ETP: `An Effluent Treatment Plant (ETP) is designed to treat the industrial wastewater generated by a manufacturing process before it is discharged or reused. Because trade effluent varies widely in strength and composition, an ETP combines physical, chemical and biological stages selected for that specific effluent, so the treated stream consistently meets the discharge standards set by the pollution control board.`,
  WTP: `A Water Treatment Plant (WTP) treats raw water — from a borewell, river or municipal supply — to make it fit for its intended use, whether drinking, process feed or boiler make-up. Treatment typically combines clarification, filtration and disinfection, with additional stages such as softening or reverse osmosis added where the raw water's hardness or dissolved solids demand it.`,
};

/** Plant types a Project Proposal document exists for. The wizard restricts to these;
 *  others fall through to the generic layout rather than printing STP copy under an
 *  unrelated heading. */
export const PROJECT_REPORT_PLANT_TYPES = ["STP", "ETP", "WTP"] as const;

export const DEFAULT_DOC_PLANT_ABOUT = `A Sewage Treatment Plant (STP) is a critical infrastructure for processing and purifying domestic and municipal wastewater. It employs a combination of physical, biological, and chemical processes to remove contaminants and pollutants, ensuring that treated water can be safely discharged into the environment or reused. STPs are essential for safeguarding public health, protecting water bodies, and promoting sustainable wastewater management practices.`;

export const DEFAULT_DOC_CIVIL_DESIGN = `The civil design of a Sewage Treatment Plant (STP) layout involves calculating dimensions for key units such as the bar screen chamber, anaerobic digester, collection tank, biological reactor, filter feed tank, treated water tank, sludge digester and pump room based on peak flow rates, retention times and space available. We have attached the schematic layout of the STP with this proposal.`;

export const DEFAULT_DOC_MEP_DESIGN = `MEP design for a Sewage Treatment Plant (STP) involves the detailed engineering of mechanical, electrical, and plumbing systems to ensure efficient wastewater processing and energy optimization. The process begins with process flow diagrams and hydraulic calculations, followed by the selection of specific equipment such as pumps, blowers, and chemical dosing systems.`;

export const DEFAULT_DOC_TAXES_DUTIES = `• All taxes for the works need to be paid as per the law, along with the payment.
• Insurance to be covered by the client.
• No extra charges are levied for Packing & Forwarding and Freight & Handling.

Sales Tax on Works Contract:
The price is exclusive of sales tax and excise duty of any kind that is applicable on works contract and turnover tax. These taxes/duties, if applicable, shall be reimbursed to us or our sub-contractors on payment of the whole or part of the contract as may be determined and assessed by the sales tax authorities from time to time.`;

export const DEFAULT_DOC_SUPPLY_ERECTION = `• All the material will be supplied to the site 45 days from the day we receive the order and the advance amount. The client needs to arrange the room or space to place the material. The room or space should be closed and not affected by rain, storm or theft.
• After the required and recommended civil works are completed, our MEP team will start the erection work. The work will be managed and supervised by our Engineer/Executive. During erection the client needs to arrange the necessary provisions such as the electrical connection. Our Engineer/Executive will coordinate with you throughout the erection period. On successful completion of the erection work we will inform you what needs to be done before testing starts.
• On completion of erection of all the quoted equipment and their accessories, M/s. Green Ecocare shall inform the client in writing that we are ready to conduct the Acceptance Tests of the various equipment, to prove that the equipment has been supplied as per the contract and has been satisfactorily and properly installed.
• No-load tests shall be performed on individual equipment. On successful completion of the tests, the contractor shall rectify any defect observed during the tests to the satisfaction of the client.
• One of our technicians will be available to commission the plant and to carry out the guarantee tests. Operating staff, labour, consumables and other utilities are to be provided by the client, free of cost.
• On successful completion of the test and upon receipt of the Preliminary Acceptance Test Certificate, the contractor will inform the client in writing that he is ready to take up the commissioning activities.
• Commissioning will be deemed completed when the plant is observed over a period of 72 hours (seventy-two hours) achieving the guaranteed performance.
• If the effluent is not available at the specified inflow rate and characteristics, commissioning activities will be carried out for the prevailing conditions, and the plant will be operated at these conditions for a period of 72 hours (seventy-two hours).`;

export const DEFAULT_DOC_WARRANTY = `The equipment shall be governed by our warranty for a period of twelve months from the date of supply.`;

export const DEFAULT_DOC_SCOPE_GREENECOCARE = `• Process design based on the operating data and parameters provided.
• Supply of civil drawings with all details within 10 days from the date of the P.O. and advance.
• Supply of mechanical, electrical and biological components within 45 days from the date of receiving the mobilization advance; all material will come as a single lot from Coimbatore to site.
• Providing plumbing pipes, cabling and connections inside and around the STP plant is our scope (all under installation work).
• Erection and commissioning will be completed within 10 days after all civil works are finished.
• We will give thorough training to your personnel on the functioning of the plant.
• The bacterial cultures supplied with the initial cost will last up to 3 months; thereafter the client needs to purchase them from us.
• All equipment carries a one-year warranty from the date of commissioning. (If there are limitations in the incoming power supply to the STP, or in the absence of proper maintenance, this warranty will not apply.)`;

export const DEFAULT_DOC_SCOPE_CLIENT = `• Civil works for the bar screen chamber, equalization tank, aeration tank, pre-filtration tank, sludge digester, sludge drying bed, treated water tank and pump room, all of which are RCC tanks. Any specified trenches required around the STP are also to be done.
• Water proofing of all tanks and provision of MS or FRP manhole covers.
• Cleaning of all tanks after finishing the civil works.
• Connection of the final sewer line from the building to the STP.
• Incoming electrical cable of the specified size from your nearest panel board to inside the pump room of the STP; power, lighting and clean water inside the tank at the time of installation.
• Maintenance of the STP with your own manpower from the date of commissioning.
• Obtaining STP-related government approvals.
• Issuing the E-Sugam form at the time of material supply.
• Disposal of treated water from the STP to the endpoint.
• Arrangement of required consumables (hypo solution etc.) from the date of commissioning of the STP.
• Provision of an extra pump of the required capacity for reusing treated water for gardening and flushing purposes.
• 24-hour power supply to the STP from the date of commissioning.
• Provision of an acoustic door to the pump room.
• Provision of earthing to the STP panel board.
• Provision of core cutting, chipping and helpers.

The bacterial consumable supplied as an augmenter for the project has been supplied for STABILISATION only. Thereafter the customer has to purchase it for the continued maintenance dosage throughout operations, as recommended.`;

export const DEFAULT_DOC_POINTS_TO_NOTE = `1. The GST will be 18% extra.
2. As far as the sewage treatment plant is concerned, this is not a product, it is a project — so it is better to go with the supplier's civil drawings in order to achieve the required result and easy maintenance.
3. Please let us know clearly about the invert level before execution of the civil works. If the invert level goes more than 3 feet, it is better to provide a collection tank and two extra pumps (cost of the pumps will be extra) to pump the sewage into the equalization/aeration tank.
4. The whole plant is designed in such a way that the water overflows from one process to the next by gravity, so we require a proper disposal option for treated water other than gardening and the ground water recharging system.
5. Any miscellaneous charges, municipal charges or PCB charges need to be borne by the promoter. If the promoter provides all the documents and fees, we will obtain the consent.
6. Proper provision for treated water should be made, because we cannot fully depend on soak pits.
7. If required, we need to provide trenches around the STP for laying cables, air and water pipes.
8. There should be a separate oil and grease trap near the kitchen, dining and canteen wash areas.
9. Dumping of food waste should be avoided.`;

export const DEFAULT_DOC_SIGNATORY_NAME = "A. Sankar";
export const DEFAULT_DOC_SIGNATORY_TITLE = "Director";
export const DEFAULT_DOC_SIGNATORY_PHONE = "8122773433";

export interface RecentProject {
  client: string;
  project: string;
  plant: string;
  technology: string;
  capacity: string;
}

/** §15 — from the client's own sample. Editable in Settings as they win more work. */
export const DEFAULT_DOC_RECENT_PROJECTS: RecentProject[] = [
  {
    client: "JK Constructions, Vellore",
    project: "Government Hospital, Anaicut",
    plant: "Sewage Treatment Plant",
    technology: "MBBR",
    capacity: "200 KLD",
  },
  {
    client: "JK Constructions, Vellore",
    project: "Government Hospital, Anaicut",
    plant: "Effluent Treatment Plant",
    technology: "pH Correction & Disinfection",
    capacity: "15 KLD",
  },
];

/**
 * The cover letter / "Greetings" page. Per-deal (it names the capacity), so this is
 * a TEMPLATE with placeholders rather than a fixed company field — the wizard seeds
 * a proposal's `coverLetter` from it and the admin can then edit that copy freely.
 */
export function defaultCoverLetter(input: { plantType: string; capacityLPD: number }): string {
  const lpd = input.capacityLPD > 0 ? `${input.capacityLPD.toLocaleString("en-IN")} litres per day` : "the required";
  return `Dear Sirs,

We thank you, your team members and your esteemed office for the kind courtesy extended to us when we visited you, for the interactions and the time transacted, and also for considering us for delivering environmental engineering solutions as per the need envisaged.

With reference to the discussions and as per your suggestion, we are placing a technical, engineering and pricing note for a ${lpd} facility. As you are aware, this treatment plant we propose to you is a unique combination of Engineering and Biotechnology — bacterial cultures for better degradation of all substances, which we refer to as Advanced Bioengineering.

The treated water can be used for gardening purposes, ground water recharging or for safe disposal, which would adhere to the discharge standards.

We will be providing all the design and civil drawings to you on confirmation of the order.

We look forward to the pleasure of working with you on this technology to solve your wastewater treatment needs.`;
}

/** §10.1 — the four rolled-up quotation lines the Project Report prices against.
 *  Stored as BOQItem rows so subtotal/GST/grandTotal and the Won→Order milestone
 *  derivation are completely untouched; only the print grouping differs. */
export const PROJECT_REPORT_COST_BUCKETS = [
  "Design and Detailed Engineering",
  "Mechanical Equipment's, Control Valves & Fitting Pipes",
  "Electrical and Instrumentation",
  "Erection, Commissioning & Supervisory Charges",
] as const;

/** §6.2 / §6.3 — default inlet and anticipated-outlet parameters from the samples. */
export const DEFAULT_INLET_PARAMETERS = [
  { parameter: "pH", value: "6.50 - 7.50" },
  { parameter: "BOD", value: "300 - 400 ppm" },
  { parameter: "COD", value: "700 - 800 ppm" },
  { parameter: "TSS", value: "More than 40 mg/L" },
];

export const DEFAULT_OUTLET_PARAMETERS = [
  { parameter: "pH", value: "6.50 - 7.50" },
  { parameter: "BOD", value: "< 20 ppm" },
  { parameter: "COD", value: "< 100 ppm" },
  { parameter: "TSS", value: "< 2 mg/L" },
];

// ---------------------------------------------------------------------------
// Section precedence — resolves two real collisions before Phase C renders them
// ---------------------------------------------------------------------------

/**
 * COLLISION 1 — Terms & Conditions vs the numbered document sections.
 *
 * `DEFAULT_STANDARD_TERMS` (v29, printed as its own page-break section from
 * `ProposalVersion.terms`) contains blocks titled Taxes & Duties, Warranty, Scope of
 * Work by Green Ecocare and Acceptance/Commissioning. Phase B added those same four as
 * dedicated company fields, which a Project Report prints as §10.2 / §12 / §13 / §11.
 * Rendering both would duplicate a page of boilerplate in the client's PDF.
 *
 * Rule: for a **Project Proposal**, the numbered sections win and the generic T&Cs page
 * is suppressed — UNLESS the admin has actually customised `terms` for this deal, in
 * which case that edit is intentional and must still print. Every other proposal type
 * has no numbered sections, so its T&Cs page always prints (it's the only place that
 * content appears at all).
 */
export function shouldPrintStandardTerms(input: {
  proposalType: string | null | undefined;
  /** This proposal's stored T&Cs text. */
  terms: string;
  /** The company template it was seeded from. */
  companyTemplate: string;
}): boolean {
  if (!input.terms.trim()) return false;
  if (input.proposalType !== "Project Proposal") return true;
  // Untouched copy of the template ⇒ already covered by §10.2–§14, so don't repeat it.
  return normalise(input.terms) !== normalise(input.companyTemplate);
}

/**
 * COLLISION 2 — points to note.
 *
 * v29 gave every proposal a per-proposal `pointsToNote` (AI-generated or hand-written);
 * Phase B added a company-level `docPointsToNote` holding the client's own numbered
 * list. Rule: the per-proposal text wins when present (someone wrote it for this deal),
 * otherwise the company standard is used. Never both.
 */
export function resolvePointsToNote(
  proposalPointsToNote: string | null | undefined,
  companyPointsToNote: string,
): string {
  return proposalPointsToNote?.trim() ? proposalPointsToNote : companyPointsToNote;
}

function normalise(s: string): string {
  return s.replace(/\s+/g, " ").trim();
}

// ---------------------------------------------------------------------------
// AMC Quotation boilerplate (the client's "AMC Quotation for STP & ETP" format)
// ---------------------------------------------------------------------------
//
// Deliberately constants rather than 14 more `Company.doc*` columns: these seed a
// new AMC's own `documentData` at creation and are then editable per proposal,
// because an AMC's exclusions genuinely vary by site (who disposes the sludge, who
// pays the electricity). A company-level copy would have to be overridden on most
// deals anyway. Same reasoning as the per-technology template blocks.

/** The sample's 11 numbered scope notes, verbatim. */
export const DEFAULT_AMC_NOTES = `1. All spares cost included in this offer.
2. All chemicals and consumables included in this offer.
3. The treated water disposal arrangements have to be properly done by the customer.
4. The customer has to arrange for solid waste disposal which is collected in the inlet of the STP.
5. Lighting in and around the STP is not our scope.
6. Cleaning of bushes in and around the STP is not our scope.
7. Any maintenance related to civil structures and infrastructure is not our scope.
8. The electricity bills are not our scope.
9. The customer has to bear all Pollution Control Board charges, if any.
10. Tank cleaning charges and sludge drying bed cleaning charges are customer scope.
11. If any new equipment or machinery is to be added to the STP as per the Pollution
    Control Board's recommendation, it will be customer scope.`;

/**
 * The four charge lines every AMC in the sample quotes, as editable defaults.
 *
 * They carry NO rate — a per-month figure is per-deal, and a fabricated one is the
 * ₹0 mistake rejected in v38. The admin fills the rate; qty is the contract's own
 * month count, so the printed "per month × months = per year" table and the stored
 * subtotal are the same numbers.
 */
export const DEFAULT_AMC_CHARGE_LINES: { description: string }[] = [
  {
    description:
      "Operating cost for the operators (per shift one operator, 3 shifts per day, so 3 operators per day)",
  },
  { description: "Consumables required to run the plant smoothly" },
  {
    description:
      "Machinery and equipment maintenance with required spares and fittings, including fixing labour charges",
  },
  {
    description:
      "Monthly one visit by an engineer, who will evaluate the plant and report on its status. Raw and treated water testing with a report for the STP/ETP.",
  },
];

/** The line printed under the charge table. Restates the term rather than
 *  hardcoding "1 year", so a 24-month AMC doesn't print a false statement. */
export function amcRatesValidityNote(termMonths: number | null | undefined): string {
  const m = termMonths && termMonths > 0 ? termMonths : 12;
  if (m === 12) return "The above rates are for 1 year only.";
  if (m % 12 === 0) return `The above rates are for ${m / 12} years only.`;
  return `The above rates are for ${m} months only.`;
}
