import { randomUUID } from "crypto";
import path from "path";
import { writeFile, mkdir } from "fs/promises";
import { env } from "./env";

/**
 * Storage adapter (Phase 0). `local` writes to public/uploads (dev only —
 * files are lost on redeploy). `s3` writes to any S3-compatible bucket
 * (AWS S3, Cloudflare R2, MinIO). Enforces a size ceiling and a MIME/extension
 * allowlist so the endpoint can't be used to fill disk or host arbitrary files.
 */

export class UploadError extends Error {
  constructor(
    message: string,
    public status: number,
  ) {
    super(message);
    this.name = "UploadError";
  }
}

const ALLOWED_MIME = [/^image\/(jpeg|png|webp|gif|heic|heif)$/, /^application\/pdf$/];
/** CAD drawings often arrive as octet-stream — gate those on extension instead. */
const ALLOWED_EXT = [".dwg", ".dxf"];

function safeExt(filename: string): string {
  const ext = path.extname(filename).toLowerCase().slice(0, 10);
  return /^\.[a-z0-9]+$/.test(ext) ? ext : "";
}

function assertAllowed(file: File) {
  if (file.size === 0) throw new UploadError("Empty file", 400);
  if (file.size > env.maxUploadBytes) {
    throw new UploadError(`File too large (max ${Math.round(env.maxUploadBytes / 1024 / 1024)}MB)`, 413);
  }
  const ext = safeExt(file.name);
  const mimeOk = ALLOWED_MIME.some((re) => re.test(file.type));
  const extOk = ALLOWED_EXT.includes(ext);
  if (!mimeOk && !extOk) {
    throw new UploadError(`Unsupported file type: ${file.type || ext || "unknown"}`, 415);
  }
}

/** Validate + persist an uploaded file. Returns a URL the app can render. */
export async function saveUpload(file: File, prefix = "uploads"): Promise<{ url: string; name: string; size: number }> {
  assertAllowed(file);
  const key = `${prefix}/${randomUUID()}${safeExt(file.name) || ".bin"}`;
  const bytes = Buffer.from(await file.arrayBuffer());

  const url = env.storageDriver === "s3" ? await putS3(key, bytes, file.type) : await putLocal(key, bytes);
  return { url, name: file.name, size: file.size };
}

/**
 * Persist server-generated bytes (e.g. a rendered PDF) at an explicit key.
 * Bypasses the upload allowlist because the caller — not an HTTP client —
 * produced the bytes and controls the content type. Same local/s3 routing.
 */
export async function putObject(key: string, bytes: Buffer, contentType: string): Promise<string> {
  return env.storageDriver === "s3" ? putS3(key, bytes, contentType) : putLocal(key, bytes);
}

async function putLocal(key: string, bytes: Buffer): Promise<string> {
  const full = path.join(process.cwd(), "public", key);
  await mkdir(path.dirname(full), { recursive: true });
  await writeFile(full, bytes);
  return `/${key}`;
}

async function putS3(key: string, bytes: Buffer, contentType: string): Promise<string> {
  const { S3Client, PutObjectCommand } = await import("@aws-sdk/client-s3");
  const client = new S3Client({
    region: env.s3Region,
    endpoint: env.s3Endpoint,
    credentials: { accessKeyId: env.s3AccessKey, secretAccessKey: env.s3SecretKey },
    forcePathStyle: true, // MinIO / R2 friendly
  });
  await client.send(
    new PutObjectCommand({
      Bucket: env.s3Bucket,
      Key: key,
      Body: bytes,
      ContentType: contentType || "application/octet-stream",
    }),
  );
  const base = env.s3PublicUrl || `${env.s3Endpoint.replace(/\/$/, "")}/${env.s3Bucket}`;
  return `${base.replace(/\/$/, "")}/${key}`;
}
