import { notFound } from "next/navigation";
import { getSession } from "@/lib/auth";
import { getMonthlyReceivables } from "@/server/services/reports";
import { formatINR } from "@/lib/money";
import { env } from "@/lib/env";

export const dynamic = "force-dynamic";

/** A6 · Printable monthly receivables report. Admin-session authed (opened by a logged-in admin). */
export default async function ReceivablesPrint({ params }: { params: Promise<{ month: string }> }) {
  const { month } = await params;
  const m = /^(\d{4})-(\d{2})$/.exec(month);
  if (!m) notFound();

  let session;
  try {
    session = await getSession();
  } catch {
    notFound();
  }
  if (session.role !== "ADMIN") notFound();

  const rep = await getMonthlyReceivables(session, Number(m[1]), Number(m[2]) - 1);
  const cell: React.CSSProperties = { padding: "6px 10px", borderBottom: "1px solid #ddd", textAlign: "left" };
  const num: React.CSSProperties = { ...cell, textAlign: "right", fontVariantNumeric: "tabular-nums" };

  return (
    <div>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", borderBottom: "2px solid #0b5e39", paddingBottom: 12 }}>
        <div>
          <div style={{ fontSize: 22, fontWeight: 700, color: "#0b5e39" }}>Green Ecocare Pvt Ltd</div>
          <div style={{ fontSize: 13, color: "#555" }}>Receivables Report — {rep.label}</div>
        </div>
        <div style={{ fontSize: 12, color: "#777" }}>{env.companyGstin || ""}</div>
      </div>

      <table style={{ width: "100%", borderCollapse: "collapse", marginTop: 20, fontFamily: "system-ui, sans-serif", fontSize: 14 }}>
        <tbody>
          <tr><td style={cell}>Collected this month</td><td style={num}>{formatINR(rep.collected)}</td></tr>
          <tr><td style={cell}>Invoiced this month</td><td style={num}>{formatINR(rep.invoiced)}</td></tr>
          <tr><td style={cell}>Milestones due this month</td><td style={num}>{formatINR(rep.dueThisMonth)}</td></tr>
          <tr><td style={cell}>Collection efficiency</td><td style={num}>{rep.efficiencyPct ?? "—"}%</td></tr>
          <tr><td style={{ ...cell, fontWeight: 700 }}>Total outstanding</td><td style={{ ...num, fontWeight: 700 }}>{formatINR(rep.outstanding)}</td></tr>
        </tbody>
      </table>

      <h3 style={{ marginTop: 24, fontFamily: "system-ui, sans-serif" }}>Outstanding by age</h3>
      <table style={{ width: "100%", borderCollapse: "collapse", fontFamily: "system-ui, sans-serif", fontSize: 14 }}>
        <tbody>
          {Object.entries(rep.aging).map(([bucket, amt]) => (
            <tr key={bucket}>
              <td style={cell}>{bucket} days</td>
              <td style={num}>{formatINR(amt)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <h3 style={{ marginTop: 24, fontFamily: "system-ui, sans-serif" }}>Top overdue clients</h3>
      <table style={{ width: "100%", borderCollapse: "collapse", fontFamily: "system-ui, sans-serif", fontSize: 14 }}>
        <tbody>
          {rep.topOverdue.length === 0 && (
            <tr><td style={cell}>No overdue clients 🎉</td></tr>
          )}
          {rep.topOverdue.map((c, i) => (
            <tr key={c.client}>
              <td style={cell}>{i + 1}. {c.client}</td>
              <td style={num}>{formatINR(c.balance)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <p style={{ marginTop: 28, fontSize: 11, color: "#999", fontFamily: "system-ui, sans-serif" }}>
        Generated by Green Ecocare CRM · Press Cmd/Ctrl+P to save as PDF.
      </p>
    </div>
  );
}
